name: Build test
on:
  push:
    branches:
    - "*"

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [alpine, debian]
        arch: [amd64, arm64]
        include:
        - os: alpine
          osgroup: linux
          opts: "--tag-libc"
        - os: debian
          osgroup: linux

    runs-on: ${{ matrix.os }}-${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: npm install --ignore-scripts

      - name: Install prerequisits
        run: |
          if [ ${{ matrix.os }} == debian ]; then
            apt-get install -y libcurl4-openssl-dev
          fi

      - name: Prebuild
        run: npx prebuildify --napi --strip ${{ matrix.opts }}
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          path: prebuilds/
          retention-days: 1
